version: '3'
services:
  v2ray:
    image: v2fly/v2fly-core
    restart: always
    volumes:
      - ./v2ray-server.json:/etc/v2ray/config.json
    command: run -c /etc/v2ray/config.json
    logging:
      driver: "local"

  caddy:
    image: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/data/caddy
    ports:
      - 80:80
    environment:
      - DOMAIN=${DOMAIN}
    depends_on:
      - v2ray
    healthcheck:
      test: ["CMD-SHELL", "test -d /data/caddy/certificates/*/${DOMAIN}"]
      interval: 1s
      retries: 60
    logging:
      driver: "local"

  trojan:
    image: trojangfw/trojan
    restart: always
    ports:
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - ./trojan-server.json:/config/config_template.json
      - ./caddy/certificates/acme-v02.api.letsencrypt.org-directory:/certificates
    command: >-
      /bin/ash -c "cp config_template.json config.json &&
        sed -e "s@CERT_PATH@/certificates/${DOMAIN}/${DOMAIN}.crt@g" -i config.json &&
        sed -e "s@KEY_PATH@/certificates/${DOMAIN}/${DOMAIN}.key@g" -i config.json &&
        exec trojan config.json"
    links:
      - caddy:__DOCKER_CADDY__
    depends_on:
      caddy:
        condition: service_healthy
    logging:
      driver: "local"

