version: "3"
services:
  setup:
    container_name: setup
    image: alpine
    command: /bin/ash /conf_gen.sh
    volumes:
      - ./users.json:/users.json
      - ./v2ray-server.json:/v2ray-server.json
      - ./conf_gen.sh:/conf_gen.sh
      - conf:/conf

  v2fly:
    container_name: v2fly
    depends_on:
      - setup
    image: v2fly/v2fly-core
    restart: always
    volumes:
      - conf:/conf
    command: run -c /conf/v2ray-server.json
    logging:
      driver: "json-file"
      options:
       max-file: "3"
       max-size: "100m"
    environment:
      - TZ=Asia/Shanghai

  caddy:
    container_name: caddy
    image: caddy
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy:/data/caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
    logging:
      driver: "local"

  filebeat:
    container_name: filebeat
    hostname: ${HOSTNAME}
    user: root
    image: docker.elastic.co/beats/filebeat:${FILEBEAT_VERSION}
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 200M
    logging:
      driver: "json-file"
      options:
       max-file: "3"
       max-size: "100m"
    restart: unless-stopped
    command:
      - "-e"
    environment:
      - TZ=Asia/Shanghai
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

volumes:
  conf:
    driver: local