filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            equals:
              docker.container.name: v2fly
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

        - condition:
            equals:
              docker.container.name: hysteria
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

        - condition:
            equals:
              docker.container.name: hysteria-access
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

        - condition:
            equals:
              docker.container.name: anytls-access
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
  ssl.verification_mode: none
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  index: "proxy-access-v2-%{+yyyyMM}"
  pipelines:
    - pipeline: "hysteria-log"
      when.equals:
        container.name: "hysteria"
    - pipeline: "hysteria-access-v2"
      when.equals:
        container.name: "hysteria-access"
    - pipeline: "anytls-log-v2"
      when.equals:
        container.name: "anytls-access"
    - pipeline: "v2fly-access-v2"
      when.equals:
        container.name: "v2fly"

setup.template.enabled: false

setup.ilm.enabled: false

# logging.level: debug
